language: python
dist: xenial

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov

stages:
  - test
  - name: deploy

jobs:
  fast_finish: true

  include:
    - python: 3.8
      env: TOXENV=black,flake8
    - python: 3.6
    - python: 3.7
    - python: 3.8
    
    - stage: deploy
      script: skip
      python: 3.7
      after_success: true
      deploy:
        provider: pypi
        user: __token__
        on:
          tags: true
          branch: master
          password:
            secure: SlrGscNHmEAzE+FdRdCCE1SW7Vl4/Hy6+CO9IJLEwWCPbv+1QOQgrZ8dSyOyeOAtL0yJokz8ieIy1WgMKytY+Bao0lQ6WV2kcSxmt9v7GxZskIfXIsOQ26W/jbhAWvr2uRhCVMZOSswbOLJjbbzAfD62N/3iw/O0qDvJsm6j/1ZidS8HZYWZ+DOT1dRHpH3lk/x5ca2Z03pPGe78zLOmrv3t0Y4Ye9jY/sd9LN/aMjQzAKvN1u887VzkPodvlWPmcSbfkD/FY1N4Wg8NX25yopF/pS/i/Kza3mF9asBVFGYxIW/VuzdXfCaeMk6eUcOj52f5+pWt+FLnfEr2mVYnFT+/VvtEpCsRtzWgwUATct5Z0hGbESo3So2TNitubEyttOGT2fZcG33YckHi7BY00DwrW+cOISG7e0B5mziHuLRq8cMobN5RKVuqDn6jK8Ex9PAxXwFWGTHCCKnTrhNBbpciwNjVuXLuHFJhi4F5DJgEYRjLLNTqchp8X8WT5lNSh6rfnhm7PKIY4Mt8tXwayBJSdCxP31XvqDPRNsrrG2+Erh20gsFKQkuD7iLEXqKDqXJB9VgwkqR7aIsHounueG61XY1F3+BQH9aWkWLUaf1K9VX3o0zmSkQellbBxaela4vYqi7SAox/wRehRSTN9zNEbsZ32L6r/EGMoJpJKs4=
